### ISSUE TITLE
'Unable to open logs' error.

### ISSUE THREAD

**Issue by markodea** [iconoeugen/docker-gitweb#2] opened 2017-03-26 07:07 UTC
I've tried to follow your instructions, but when I start the docker container, I get the following messages:

```
Initialize empty Git repository in /var/lib/git/dummy.git
Initialized empty Git repository in /var/lib/git/dummy.git/
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00091: httpd: could not open error log file /etc/httpd/logs/error_log.
AH00015: Unable to open logs
```

Thanks
Mark.

**Comment by iconoeugen** [comment] 2017-03-26 12:38
Can you please provide an exact command line that you user to start the container?

I was not able to reproduce your issue using the commands:

``` bash
$ docker build -t gitweb_gitweb .
$ docker run -it --name gitweb_test -p 8080:8080 gitweb_gitweb
```
and tested with:

``` bash
$ git clone http://localhost:8080/git/dummy
Cloning into 'dummy'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```

**Comment by iconoeugen** [comment] 2018-03-12 16:17
Closing this issues as no feedback was provided

**Closed as completed by iconoeugen** 2018-03-12 16:17 UTC
